# Generated by Django 3.2.3 on 2021-05-31 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('address_one', models.CharField(max_length=100, null=True)),
                ('address_two', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state_or_province', models.CharField(max_length=50, null=True)),
                ('postal_code', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('shipping_method', models.CharField(choices=[('Express-2 Day', 'Express-2 Day'), ('Express-4 Day', 'Express-4 Day'), ('Express-7 Day', 'Express-7 Day')], max_length=20, null=True)),
                ('save_for_future', models.BooleanField(blank=True, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.customerprofile')),
            ],
        ),
    ]
