# Generated by Django 3.2.3 on 2021-06-05 07:06

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210604_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaviscoPrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('sub_header', models.CharField(max_length=200)),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='LaviscoReturnRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('sub_header', models.CharField(max_length=200)),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='LaviscoTermsCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('sub_header', models.CharField(max_length=200)),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
        migrations.RenameModel(
            old_name='LaviscoTermsConditions',
            new_name='LaviscoDelivery',
        ),
        migrations.AlterField(
            model_name='laviscoprofile',
            name='terms_conditions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.laviscotermscondition'),
        ),
    ]
