# Generated by Django 3.2.3 on 2021-06-07 14:53

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210605_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='meta_desc',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerorder',
            name='meta_keywords',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerorder',
            name='meta_title',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerorder',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='meta_desc',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='meta_keywords',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='meta_title',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='user.name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='meta_desc',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='meta_keywords',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='meta_title',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laviscoaboutus',
            name='meta_desc',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laviscoaboutus',
            name='meta_keywords',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laviscoaboutus',
            name='meta_title',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laviscoaboutus',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='header'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laviscocontactus',
            name='meta_desc',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laviscocontactus',
            name='meta_keywords',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laviscocontactus',
            name='meta_title',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laviscocontactus',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='header'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laviscocookiepolicy',
            name='meta_desc',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laviscocookiepolicy',
            name='meta_keywords',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laviscocookiepolicy',
            name='meta_title',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laviscocookiepolicy',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='header'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laviscodelivery',
            name='meta_desc',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laviscodelivery',
            name='meta_keywords',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laviscodelivery',
            name='meta_title',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laviscodelivery',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='header'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laviscofaq',
            name='meta_desc',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laviscofaq',
            name='meta_keywords',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laviscofaq',
            name='meta_title',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laviscofaq',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='header'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laviscoprivacypolicy',
            name='meta_desc',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laviscoprivacypolicy',
            name='meta_keywords',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laviscoprivacypolicy',
            name='meta_title',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laviscoprivacypolicy',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='header'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laviscoreturnrefund',
            name='meta_desc',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laviscoreturnrefund',
            name='meta_keywords',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laviscoreturnrefund',
            name='meta_title',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laviscoreturnrefund',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='header'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laviscotermscondition',
            name='meta_desc',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laviscotermscondition',
            name='meta_keywords',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laviscotermscondition',
            name='meta_title',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laviscotermscondition',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='header'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='meta_desc',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='meta_keywords',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='meta_title',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='user.name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipping',
            name='meta_desc',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipping',
            name='meta_keywords',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipping',
            name='meta_title',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipping',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='first_name'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LaviscoProfile',
        ),
    ]
