# Generated by Django 3.2.3 on 2021-06-08 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerorder',
            options={'verbose_name': 'Customer Order', 'verbose_name_plural': 'Customer Orders'},
        ),
        migrations.AlterModelOptions(
            name='customerprofile',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': ' Users'},
        ),
        migrations.AlterModelOptions(
            name='laviscoaboutus',
            options={'verbose_name': 'About Us', 'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterModelOptions(
            name='laviscocontactus',
            options={'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contact Us'},
        ),
        migrations.AlterModelOptions(
            name='laviscocookiepolicy',
            options={'verbose_name': 'Cookie Policy', 'verbose_name_plural': 'Cookie Policies'},
        ),
        migrations.AlterModelOptions(
            name='laviscodelivery',
            options={'verbose_name': 'Delivery', 'verbose_name_plural': 'Deliveries'},
        ),
        migrations.AlterModelOptions(
            name='laviscofaq',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterModelOptions(
            name='laviscoprivacypolicy',
            options={'verbose_name': 'Privacy Policy', 'verbose_name_plural': 'Privacy Policies'},
        ),
        migrations.AlterModelOptions(
            name='laviscoreturnrefund',
            options={'verbose_name': 'Return & Refund', 'verbose_name_plural': 'Returns & Refunds'},
        ),
        migrations.AlterModelOptions(
            name='laviscotermscondition',
            options={'verbose_name': 'Term & Condition', 'verbose_name_plural': 'Terms & Conditions'},
        ),
        migrations.AlterModelOptions(
            name='sellerprofile',
            options={'verbose_name': 'Seller', 'verbose_name_plural': 'Sellers'},
        ),
        migrations.AlterModelOptions(
            name='shipping',
            options={'verbose_name': 'Shipping', 'verbose_name_plural': 'Shipping'},
        ),
        migrations.AlterModelTable(
            name='customerorder',
            table='Customer Order',
        ),
        migrations.AlterModelTable(
            name='customerprofile',
            table='Customer',
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='User',
        ),
        migrations.AlterModelTable(
            name='laviscoaboutus',
            table='About Us',
        ),
        migrations.AlterModelTable(
            name='laviscocontactus',
            table='Contact Us',
        ),
        migrations.AlterModelTable(
            name='laviscocookiepolicy',
            table='Cookie Policy',
        ),
        migrations.AlterModelTable(
            name='laviscodelivery',
            table='Delivery',
        ),
        migrations.AlterModelTable(
            name='laviscofaq',
            table='FAQ',
        ),
        migrations.AlterModelTable(
            name='laviscoprivacypolicy',
            table='Privacy Policy',
        ),
        migrations.AlterModelTable(
            name='laviscoreturnrefund',
            table='Return & Refund',
        ),
        migrations.AlterModelTable(
            name='laviscotermscondition',
            table='Term & Condition',
        ),
        migrations.AlterModelTable(
            name='sellerprofile',
            table='Seller',
        ),
        migrations.AlterModelTable(
            name='shipping',
            table='Shipping',
        ),
    ]
