# Generated by Django 3.2.3 on 2021-06-22 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210608_1155'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LaviscoTermsCondition',
            new_name='LaviscoStaticContent',
        ),
        migrations.DeleteModel(
            name='LaviscoAboutUs',
        ),
        migrations.DeleteModel(
            name='LaviscoContactUs',
        ),
        migrations.DeleteModel(
            name='LaviscoCookiePolicy',
        ),
        migrations.DeleteModel(
            name='LaviscoDelivery',
        ),
        migrations.DeleteModel(
            name='LaviscoFAQ',
        ),
        migrations.DeleteModel(
            name='LaviscoPrivacyPolicy',
        ),
        migrations.DeleteModel(
            name='LaviscoReturnRefund',
        ),
        migrations.AlterModelOptions(
            name='laviscostaticcontent',
            options={'verbose_name': 'Static Content', 'verbose_name_plural': 'Static Content'},
        ),
        migrations.AlterModelTable(
            name='laviscostaticcontent',
            table='Static Content',
        ),
    ]
