# Generated by Django 3.2.3 on 2021-06-23 13:09

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210622_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laviscostaticcontent',
            name='content',
            field=django_quill.fields.QuillField(),
        ),
    ]
