# Generated by Django 3.2.3 on 2021-06-23 15:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_laviscostaticcontent_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laviscostaticcontent',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
