# Generated by Django 3.2.3 on 2021-06-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_laviscostaticcontent_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='laviscostaticcontent',
            name='page_key',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
