# Generated by Django 3.2.3 on 2021-05-31 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='customer',
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
    ]
